version: '3'

services:
  selenium-hub:
    image: selenium/hub:4.20.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - grid

  node-chrome:
    image: selenium/node-chrome:4.20.0
    container_name: node-chrome
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_PORT=5555
    networks:
      - grid
    depends_on:
      - selenium-hub

  node-firefox:
    image: selenium/node-firefox:4.20.0
    container_name: node-firefox
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_PORT=5556
    networks:
      - grid
    depends_on:
      - selenium-hub

networks:
  grid:
    driver: bridge
